# Generated by Django 3.2 on 2021-04-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='edit_ip',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
